name: dish_dash
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  icon_badge: ^1.0.0
  dot_navigation_bar: ^1.0.2
  flip_card: ^0.7.0
  google_fonts: ^6.1.0
  cool_alert: ^2.0.1
  flutter_otp_text_field: ^1.1.1
  animate_do: ^3.1.2
  http: ^1.1.2
  flutter_riverpod: ^2.4.9
  flutter_staggered_grid_view: ^0.7.0
  awesome_notifications: ^0.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/bank_logos/
    - assets/images/main_category/
